services:
  stackportdb:
    build:
      context: ./Docker-files/db
    image: surajbellur/stackport-db
    container_name: stackport-db
    ports:
      - "3306:3306"
    volumes:
      - stackport-db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: accounts
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123

  stackportcache01:
    image: memcached
    container_name: stackport-cache-01
    ports:
      - "11211:11211"

  stackportmq01:
    image: rabbitmq
    container_name: stackport-rmq-01
    ports:
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: test
      RABBITMQ_DEFAULT_PASS: test

  stackportapp:
    build:
      context: ./Docker-files/app
    image: surajbellur/stackport-app
    container_name: stackport-app
    ports:
      - "8080:8080"
    volumes:
      - stackport-app-data:/usr/local/tomcat/webapps

  stackportweb:
    build:
      context: ./Docker-files/web
    image: surajbellur/stackport-web
    container_name: stackport-web
    ports:
      - "80:80"

volumes:
  stackport-db-data: {}
  stackport-app-data: {}