def COLOR_MAP = [
    SUCCESS: 'good',
    UNSTABLE: 'warning',
    FAILURE: 'danger',
    ABORTED: 'danger'
]

pipeline {
    agent any
    tools {
        jdk "JDK17"
        maven "MAVEN3.9"
    }
    stages {
        stage("Fetch code"){
            steps{
                echo "========Fetching code========"
                git branch: 'atom', url: 'https://github.com/suraj-bellur/stackport.git'
            }
        }

        stage("Build"){
            steps {
                echo "========Building========"
                sh 'mvn install -DskipTests'
            }
            post {
                success {
                    echo "Archiving artifacts..."
                    archiveArtifacts artifacts: '**/*.war'
                }
            }
        }

        stage("Unit Test"){
            steps {
                echo "========Running Unit Tests========"
                sh 'mvn test'
            }
        }

        stage("code analysis with checkstyle"){
            steps {
                echo "========Running Checkstyle========"
                sh 'mvn checkstyle:checkstyle'
            }
        }

        stage("sonar code analysis"){
            environment {
                scannerHome = tool 'SONAR8.0';
            }
            steps {
                echo "========Running SonarQube Analysis========"
                withSonarQubeEnv('sonarserver') {
                    sh '''${scannerHome}/bin/sonar-scanner \
                        -Dsonar.projectKey=stackport \
                        -Dsonar.projectName=stackport-repo \
                        -Dsonar.projectVersion=1.0 \
                        -Dsonar.sources=src/ \
                        -Dsonar.java.binaries=target/classes \
                        -Dsonar.junit.reportsPath=target/surefire-reports/ \
                        -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml \
                        -Dsonar.java.checkstyle.reportPaths=target/checkstyle-result.xml'''
                }
            }
        }

        stage("Quality Gate"){
            steps {
                echo "========Checking Quality Gate Status========"
                timeout(time: 1, unit: 'HOURS') {
                    waitForQualityGate abortPipeline: true
                }
            }
        }

        stage("Publish to Nexus") {
            steps {
                nexusArtifactUploader(
                    nexusVersion: 'nexus3',
                    protocol: 'http',
                    nexusUrl: '172.31.89.137:8081',
                    groupId: 'QA',
                    version: "${env.BUILD_ID}-${env.BUILD_TIMESTAMP}",
                    repository: 'stackport-repo',
                    credentialsId: 'nexus-login-username-password',
                    artifacts: [[
                        artifactId: 'stackport',
                        classifier: '',
                        file: 'target/stackport-v2.war',
                        type: 'war'
                    ]]
                )
            }
        }
    }

    post {
        always {
            echo "========Slack Notification========"
            slackSend channel: '#jenkins-cicd',
                color: COLOR_MAP[currentBuild.currentResult],
                message: "*${currentBuild.currentResult}:* \nJob: ${env.JOB_NAME} \nBuild: ${env.BUILD_NUMBER} \n(<${env.BUILD_URL}|Open>)"
        }
    }
}